indent_width = 2
indent_type = "Spaces"
line_endings = "Unix"
column_width = 78
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Always"

[sort_requires]
enabled = true
